### ISSUE TITLE
ESP32-PICO-D4 support

### ISSUE THREAD

**Issue by testuser7** [nopnop2002/esp-idf-CANBus-Monitor#13]
Is ESP32-PICO-D4 supported?

**Comment by nopnop2002** [comment]
Yes

It supports these SoCs.

idf.py set-target {esp32/esp32s2/esp32s3/esp32c3}

**Comment by testuser7** [comment]
What GPIOs are used? Can this board be used: https://docs.m5stack.com/en/core/stamp_pico ?

**Comment by nopnop2002** [comment]
Have you ever used esp-idf?

Have you read the README?

All the information you need is in the README.

**Comment by testuser7** [comment]
> Have you ever used esp-idf?

Not yet. I'm trying to figure out if this hardware can be used.

> Have you read the README?
> 
> All the information you need is in the README.

ESP32-PICO is not listed. GPIO 21 and 22 is provided on the STAMP-PICO like in ESP32.
But UART TX and RX are on different pins (GPIO 1 and 3).

Only new target with different UART GPIO should be added?

**Comment by nopnop2002** [comment]
You don't understand ESP-IDF at all, so you don't understand anything I answered.
ESP-IDF is available for all ESP32s.
Study esp-idf with this sample first.

https://github.com/espressif/esp-idf/tree/master/examples/get-started
